### PR TITLE
Show how to use the save handler

### PR DESCRIPTION
**Pull request by rquast**
This change explains how the save handler works a bit more clearly.

### CODE REVIEW

**Comment by rquast** [comment]
Also maybe include something about how to convert the document to JSON like this?

```
    let doc = params.editorSession.getDocument()
    let jsonConverter = new JSONConverter()
    let jsonStr = JSON.stringify(jsonConverter.exportDocument(doc))
    console.log(jsonStr);
```

**Comment by rquast** [comment]
Project looks fantastic by the way. I know you're in the middle of reworking it.

**Comment by michael** [comment]
Hey good idea!

The challenge we face with the examples is keeping them minimal and not mix too many features into one example. It was tempting to demo saving as part of the image example because it includes file upload as part of a save action.

Merging this as it's a good addition. However, I think we should work towards a dedicated 'persistence' example. And a 'converter' example. If you want to help with that you are very welcome!

**Comment by rquast** [comment]
Cool! I feel like recording a video showing how it all works, but it's probably a little too early. Really like the way you use the sync/Promise.all to upload. It's really great.

**Pull request merged**
