### PR TITLE
Added CodeEditor example.

### PR DESCRIPTION
**Pull request by obuchtala**
Using ACE:
- unfortunately no browserify compatible build
- but still pretty easy to use: `npm install ace-builds` and serving statically
- seems to work together with IsolatedNodes well, out-of-the-box.

### CODE REVIEW

**Comment by obuchtala** [comment]
Plain integration:

code-editor-example

**Comment by philippamarkovics** [comment]
😍

**Comment by michael** [comment]
Do we want to get this into examples officially? Or does it cause too much troubles in terms of dependencies?

**Comment by obuchtala** [comment]
I want yes :)

will do it.

**Pull request merged**
