### PR TITLE
Updating examples

### PR DESCRIPTION
**Pull request by obuchtala**

### CODE REVIEW

**Comment by michael** [comment]
FormExample: entity-tool needs an icon then the toolbar will not be offset.

**Comment by michael** [comment]
Switching text types breaks. Ahh we need to streamline that switch text type stuff. That's whacky, and it comes to light when used extensively with isolated nodes etc.

**Comment by michael** [comment]
InputExample: Maybe this should not set the cursor immediately. You will loose the ability to click and select the whole node and delete.

**Comment by obuchtala** [comment]
right

**Comment by michael** [comment]
TableExample: Not possible to insert content into empty cells.

**Comment by obuchtala** [comment]
true. not implemented ;)

**Comment by michael** [comment]
Maybe not have them sparse but with empty cells for now? :) Just for the demo it will do.

**Comment by obuchtala** [comment]
Yep

**Comment by michael** [comment]
The prose-editor example is also dispensable maybe... or we just alter the text and instead of the poem say this is just the basic usage of the proseeditor package without extensions. However it's implicitly covered by all the other proseeditor based examples.

**Comment by obuchtala** [comment]
@michael could u try 'focused' (just pushed)

**Comment by michael** [comment]
I did. Works fine.. only the alien doesn't change color anymore ;)

**Comment by obuchtala** [comment]
REALLY? it does for me.
maybe because I know how to do aliens ;)

**Comment by michael** [comment]
Yeah i don't know how to make them angry. ;)

Insert Table node does not work.

**Pull request merged**
