### PR TITLE
Working on an example inspired by tangle (Bret Victor)

### PR DESCRIPTION
**Pull request by obuchtala**

### CODE REVIEW

**Comment by obuchtala** [comment]
image

**Comment by obuchtala** [comment]
substance-example-tange-round1

**Comment by obuchtala** [comment]
substance-example-tangle

**Comment by michael** [comment]
Should we try to merge that into devel, even if not perfect yet?

**Comment by obuchtala** [comment]
Closing this as it is now based on `develop`

**Pull request closed without merging**
